import type { Metadata } from "next";
import { Header } from "@/components/shared/Header";
import { Hero } from "@/components/shared/Hero";
import "./globals.css";
import { Footer } from "@/components/shared/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className="bg-base-gradient box-border p-0 m-0">
				<Header />
				<Hero />
				{children}
				<Footer />
			</body>
		</html>
	);
}
