import type { Metadata } from "next";
import { Header } from "@/components/shared/Header";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased bg-base-gradient box-border p-0 m-0">
				<Header />
				{children}
			</body>
		</html>
	);
}
